"""add cleaning_disabled_json

Revision ID: ae6518aa2b19
Revises: f6e3952946a5
Create Date: 2026-09-03 11:04:47.575854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6518aa2b19'
down_revision: Union[str, Sequence[str], None] = 'f6e3952946a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('cleaning_disabled_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'cleaning_disabled_json')
    # ### end Alembic commands ###
