/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description تجديد الجلسة — مع **تدوير** التوكن (الخطة §9.1).
         *
         *     كل توكن تجديد يُستهلك مرة واحدة فقط. إعادة استعماله مرفوضة، وهي في
         *     الوقت نفسه إشارة إلى أن نسخة منه بيد غير صاحبها — فتُسجَّل في سجل
         *     التدقيق.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload Url
         * @description يحجز سجل ملف ويُرجع رابط رفع. لا بايت واحد يمر من هنا.
         */
        post: operations["create_upload_url_datasets_upload_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{ticket}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Upload
         * @description مسار الرفع للتخزين المحلي فقط — بديل عن توقيع S3 في التطوير.
         *
         *     لا يستعمل CurrentUser عمداً: التذكرة الموقّعة هي الهوية هنا، تماماً كما
         *     أن الرابط الموقّع من S3 هو الهوية هناك.
         */
        put: operations["put_upload_uploads__ticket__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description يؤكّد وصول الملف للتخزين ثم يبدأ المعالجة.
         *
         *     لا نثق بكلمة العميل: نتحقق من وجود الكائن وحجمه الفعلي في التخزين.
         */
        post: operations["complete_upload_datasets__dataset_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        /**
         * Upload Dataset
         * @description يستقبل الملف، يخزّنه كما هو، ويُرجع job_id فوراً.
         *
         *     قاعدة ذهبية #6: لا معالجة هنا — المعالجة في الـworker. هذا الـendpoint
         *     مهمته النقل والتسجيل فقط.
         */
        post: operations["upload_dataset_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Concepts
         * @description المفاهيم التي يفهمها المحرك — تغذّي قائمة التصحيح في الواجهة.
         *
         *     مصدرها قاموس المحرك نفسه، فلا تعرض الواجهة خياراً لا يفهمه المحرك.
         */
        get: operations["list_concepts_datasets_concepts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Currencies
         * @description العملات التي يعرفها المحرك — تغذّي قائمة اختيار العملة في الواجهة.
         *
         *     الترتيب ليس أبجدياً بل ترتيب السجل في المحرك، وأوّله عملات السوق الأساسي.
         */
        get: operations["list_currencies_datasets_currencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Dataset
         * @description حذف نهائي للملف وكل ما اشتُقّ منه.
         *
         *     القاعدة الذهبية #3 تمنع **المعالجة** من المساس بالملف الأصلي؛ لا تمنع
         *     صاحب البيانات من حذفها. بيانات مالية للعملاء بلا زر حذف ليست ميزة أمان،
         *     بل عيب. الحذف هنا صريح، بطلب المالك، ومسجَّل في سجل التدقيق.
         */
        delete: operations["delete_dataset_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_datasets__dataset_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Schema
         * @description تصحيح المستخدم لدور عمود — الخطة §5.4 تجعل هذه الواجهة إجبارية.
         *
         *     التصحيح لا يُعدّل الـschema المحفوظة فقط: يُعاد تشغيل المعالجة من الملف
         *     الأصلي بالتصحيح مطبَّقاً، لأن كل ما بعد الدلالة يعتمد عليها (التنظيف،
         *     الأعمدة المشتقّة، التحليلات، الاكتشافات). تحديث الـschema وحدها كان
         *     سيترك أرقاماً محسوبة على فهم قديم — وهذا أسوأ من عدم التصحيح.
         */
        patch: operations["patch_schema_datasets__dataset_id__schema_patch"];
        trace?: never;
    };
    "/datasets/{dataset_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_datasets__dataset_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/cleaning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cleaning
         * @description «ماذا تغيّر في بياناتي؟» — الوصفة وسجل التغييرات معاً.
         *
         *     نُرجع المعطَّل صراحةً أيضاً: بدونه لا تعرف الواجهة أي مفتاح مطفأ الآن،
         *     فتعرض حالة خاطئة للمستخدم.
         */
        get: operations["get_cleaning_datasets__dataset_id__cleaning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Cleaning
         * @description تعطيل/تفعيل عملية تنظيف ثم إعادة التشغيل (الخطة §6.3).
         *
         *     التنظيف اقتراح لا حكم: المستخدم قد يعرف أن اسمين متشابهين هما فعلاً
         *     عميلان مختلفان. رفضه يجب أن يُعيد الحساب من الملف الأصلي، لا أن يخفي
         *     سطراً من السجل فقط.
         */
        patch: operations["patch_cleaning_datasets__dataset_id__cleaning_patch"];
        trace?: never;
    };
    "/datasets/{dataset_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["get_insights_datasets__dataset_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Job
         * @description بث تقدّم الوظيفة لحظياً (SSE).
         *
         *     التحقق من الملكية يتم **قبل** بدء البث، حتى يصل 404 كخطأ HTTP عادي لا
         *     كحدث داخل بث ناجح.
         */
        get: operations["stream_job_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description كل ما تحتاجه شاشة النظرة العامة بطلب واحد — بدل أربع رحلات من الهاتف.
         */
        get: operations["dashboard_datasets__dataset_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rows
         * @description استعراض الجدول بصفحات — لا نُنزّل 100 ألف صف على الهاتف أبداً.
         */
        get: operations["rows_datasets__dataset_id__rows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description تصدير الملف المنظَّف. CSV بـBOM ليفتح صحيحاً بإكسل العربي.
         */
        get: operations["export_datasets__dataset_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggestions
         * @description أسئلة مقترحة مبنية على أعمدة هذا الملف بالذات.
         *
         *     المحرك هو من يقرّرها: اقتراح سؤال لا يستطيع الإجابة عنه يعطي «لم أفهم»
         *     عند أول ضغطة — وهذا أسوأ انطباع أول ممكن.
         */
        get: operations["suggestions_datasets__dataset_id__suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_datasets__dataset_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warehouses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Warehouses */
        get: operations["list_warehouses_v1_warehouses_get"];
        put?: never;
        /** Create Warehouse */
        post: operations["create_warehouse_v1_warehouses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warehouses/{warehouse_id}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tokens */
        get: operations["list_tokens_v1_warehouses__warehouse_id__tokens_get"];
        put?: never;
        /** Create Token */
        post: operations["create_token_v1_warehouses__warehouse_id__tokens_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warehouses/{warehouse_id}/tokens/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Token */
        delete: operations["revoke_token_v1_warehouses__warehouse_id__tokens__token_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/warehouses/{warehouse_id}/syncs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Syncs */
        get: operations["list_syncs_v1_warehouses__warehouse_id__syncs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sync/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Catalog */
        post: operations["sync_catalog_v1_sync_catalog_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Telegram Status */
        get: operations["telegram_status_v1_alerts_telegram_get"];
        put?: never;
        post?: never;
        /** Telegram Unlink */
        delete: operations["telegram_unlink_v1_alerts_telegram_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Link */
        post: operations["telegram_link_v1_alerts_telegram_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/telegram/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Verify */
        post: operations["telegram_verify_v1_alerts_telegram_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/internal/check-stale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Internal Check Stale */
        post: operations["internal_check_stale_v1_internal_check_stale_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskIn */
        AskIn: {
            /** Question */
            question: string;
        };
        /** AskOut */
        AskOut: {
            /** Question */
            question: string;
            /** Understood As */
            understood_as: string;
            /** Answer Ar */
            answer_ar: string;
            /** Confidence */
            confidence: number;
            /** Tool */
            tool: string;
            /**
             * Metrics
             * @default []
             */
            metrics: {
                [key: string]: unknown;
            }[];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            } | null;
            /** Chart */
            chart?: {
                [key: string]: unknown;
            } | null;
            /**
             * Ai Paused Over Budget
             * @default false
             */
            ai_paused_over_budget: boolean;
        };
        /** Body_upload_dataset_datasets_post */
        Body_upload_dataset_datasets_post: {
            /** File */
            file: string;
        };
        /** ChangeLog */
        ChangeLog: {
            /** Results */
            results: components["schemas"]["OperationResult"][];
            /** Rows Before */
            rows_before: number;
            /** Rows After */
            rows_after: number;
        };
        /** CleaningOperation */
        CleaningOperation: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Target Columns */
            target_columns: string[];
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Auto Suggested
             * @default true
             */
            auto_suggested: boolean;
            /**
             * Reason Ar
             * @default
             */
            reason_ar: string;
            /**
             * Key
             * @description معرّف ثابت للعملية عبر المعالجات المختلفة.
             *
             *     ⚠️ لا نستعمل `id` لهذا: هو ترتيبي (op01, op02...) ويتغيّر لو تغيّرت
             *     الخطة — فتعطيلُ المستخدمِ عمليةً كان سيقع على عملية أخرى بعد إعادة
             *     المعالجة. النوع + الأعمدة يبقيان ثابتين لنفس الملف.
             */
            readonly key: string;
        };
        /** CleaningOut */
        CleaningOut: {
            recipe: components["schemas"]["CleaningRecipe"];
            changelog: components["schemas"]["ChangeLog"];
            /**
             * Disabled
             * @default []
             */
            disabled: string[];
        };
        /** CleaningPatchIn */
        CleaningPatchIn: {
            /** Disabled */
            disabled?: string[];
        };
        /** CleaningRecipe */
        CleaningRecipe: {
            /** Operations */
            operations: components["schemas"]["CleaningOperation"][];
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** ColumnOverrideIn */
        ColumnOverrideIn: {
            /** Column Name */
            column_name: string;
            /** Concept */
            concept?: string | null;
            /** Role */
            role?: string | null;
            /** Unit */
            unit?: string | null;
        };
        /** ColumnProfile */
        ColumnProfile: {
            /** Name */
            name: string;
            /** Position */
            position: number;
            /**
             * Inferred Type
             * @enum {string}
             */
            inferred_type: "integer" | "float" | "date" | "datetime" | "boolean" | "categorical" | "text" | "identifier" | "mixed" | "empty";
            /** Type Confidence */
            type_confidence: number;
            /** Total Count */
            total_count: number;
            /** Null Count */
            null_count: number;
            /** Null Pct */
            null_pct: number;
            /** Unique Count */
            unique_count: number;
            /** Unique Pct */
            unique_pct: number;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Mean */
            mean?: number | null;
            /** Median */
            median?: number | null;
            /** Std */
            std?: number | null;
            /** P25 */
            p25?: number | null;
            /** P75 */
            p75?: number | null;
            /** Zero Count */
            zero_count?: number | null;
            /** Negative Count */
            negative_count?: number | null;
            /** Min Date */
            min_date?: string | null;
            /** Max Date */
            max_date?: string | null;
            /** Granularity */
            granularity?: string | null;
            /** Top Values */
            top_values?: [
                string,
                number
            ][];
            /** Avg Length */
            avg_length?: number | null;
            /** Sample Values */
            sample_values?: unknown[];
            /** Quality Issues */
            quality_issues?: components["schemas"]["QualityIssue"][];
        };
        /** CompleteOut */
        CompleteOut: {
            /** Dataset Id */
            dataset_id: string;
            /** Job Id */
            job_id: string;
        };
        /** ConceptOut */
        ConceptOut: {
            /** Concept */
            concept: string;
            /** Role */
            role: string;
            /** Unit */
            unit?: string | null;
            /** Label Ar */
            label_ar: string;
        };
        /** CurrencyOut */
        CurrencyOut: {
            /** Code */
            code: string;
            /** Symbol Ar */
            symbol_ar: string;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Dataset Id */
            dataset_id: string;
            /** Kpis */
            kpis: {
                [key: string]: unknown;
            }[];
            /** Charts */
            charts: {
                [key: string]: unknown;
            }[];
            /** Insights */
            insights: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DatasetCurrency
         * @description عملة الملف — وكيف عرفناها. `code=None` مع `codes` متعددة تعني ملفاً
         *     فيه أكثر من عملة: عندها لا يوجد «الإجمالي» واحد أصلاً، بل مجموع لكل عملة.
         */
        DatasetCurrency: {
            /** Code */
            code?: string | null;
            /** Symbol Ar */
            symbol_ar?: string | null;
            /**
             * Source
             * @default none
             * @enum {string}
             */
            source: "column" | "values" | "column_name" | "user" | "none";
            /** Column */
            column?: string | null;
            /** Codes */
            codes?: string[];
            /**
             * Evidence Ar
             * @default
             */
            evidence_ar: string;
            /** Mixed */
            readonly mixed: boolean;
            /** Known */
            readonly known: boolean;
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Duplicate Of */
            duplicate_of?: string | null;
            /** Domain */
            domain: string;
            /** Detected Format */
            detected_format?: string | null;
            /** Row Count */
            row_count?: number | null;
            /** Column Count */
            column_count?: number | null;
            /** File Size */
            file_size?: number | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /** Error Ar */
            error_ar?: string | null;
        };
        /** DatasetProfile */
        DatasetProfile: {
            /** Row Count */
            row_count: number;
            /** Column Count */
            column_count: number;
            /** Duplicate Row Count */
            duplicate_row_count: number;
            /** Memory Mb */
            memory_mb: number;
            /** Columns */
            columns: components["schemas"]["ColumnProfile"][];
            /** Dataset Issues */
            dataset_issues?: components["schemas"]["QualityIssue"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Dataset Id */
            dataset_id: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
            /** Stage Ar */
            stage_ar: string;
            /** Error Ar */
            error_ar?: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string | null;
        };
        /** OperationResult */
        OperationResult: {
            /** Operation Id */
            operation_id: string;
            /** Operation Type */
            operation_type: string;
            /**
             * Rows Affected
             * @default 0
             */
            rows_affected: number;
            /**
             * Cells Changed
             * @default 0
             */
            cells_changed: number;
            /** Columns Affected */
            columns_affected?: string[];
            /** Examples */
            examples?: {
                [key: string]: unknown;
            }[];
            /**
             * Summary Ar
             * @default
             */
            summary_ar: string;
        };
        /** QualityIssue */
        QualityIssue: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "missing_values" | "duplicate_rows" | "whitespace" | "mixed_case" | "outliers" | "constant_column" | "sparse_column" | "mixed_types" | "future_dates" | "negative_values" | "arabic_indic_digits";
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Column */
            column?: string | null;
            /**
             * Affected Count
             * @default 0
             */
            affected_count: number;
            /**
             * Affected Pct
             * @default 0
             */
            affected_pct: number;
            /**
             * Message Ar
             * @default
             */
            message_ar: string;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /** RowsOut */
        RowsOut: {
            /** Columns */
            columns: string[];
            /**
             * Outlier Flags
             * @default {}
             */
            outlier_flags: {
                [key: string]: string;
            };
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total Rows */
            total_rows: number;
            /** Total Pages */
            total_pages: number;
        };
        /** SchemaPatchIn */
        SchemaPatchIn: {
            /** Columns */
            columns?: components["schemas"]["ColumnOverrideIn"][];
            /** Currency */
            currency?: string | null;
            /**
             * Set Currency
             * @default false
             */
            set_currency: boolean;
        };
        /** SchemaPatchOut */
        SchemaPatchOut: {
            /** Dataset Id */
            dataset_id: string;
            /** Job Id */
            job_id: string;
        };
        /** SemanticColumn */
        SemanticColumn: {
            /** Column Name */
            column_name: string;
            /** Concept */
            concept?: string | null;
            /**
             * Role
             * @default unknown
             * @enum {string}
             */
            role: "measure" | "dimension" | "time" | "identifier" | "flag" | "constant" | "unknown";
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Detection Method
             * @default none
             * @enum {string}
             */
            detection_method: "dictionary" | "pattern" | "cross_validation" | "derived" | "constant" | "llm" | "user" | "none";
            /** Unit */
            unit?: string | null;
            /** Currency */
            currency?: string | null;
            /**
             * Evidence Ar
             * @default
             */
            evidence_ar: string;
            /**
             * User Overridden
             * @default false
             */
            user_overridden: boolean;
        };
        /** SemanticSchema */
        SemanticSchema: {
            /** Columns */
            columns: components["schemas"]["SemanticColumn"][];
            /**
             * Domain
             * @default generic
             */
            domain: string;
            currency?: components["schemas"]["DatasetCurrency"];
        };
        /** StaleCheckOut */
        StaleCheckOut: {
            /** Stale */
            stale: number;
            /** Alerted */
            alerted: number;
        };
        /** SyncOut */
        SyncOut: {
            /** Sync Id */
            sync_id: string;
            /** Warehouse Id */
            warehouse_id: string;
            /** Duplicate */
            duplicate: boolean;
            /** Dataset Id */
            dataset_id: string | null;
            /** Job Id */
            job_id: string | null;
            stats: components["schemas"]["SyncStats"];
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
        };
        /** SyncRunOut */
        SyncRunOut: {
            /** Sync Id */
            sync_id: string;
            /** Warehouse Id */
            warehouse_id: string;
            /** Duplicate */
            duplicate: boolean;
            /** Dataset Id */
            dataset_id: string | null;
            /** Job Id */
            job_id: string | null;
            stats: components["schemas"]["SyncStats"];
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Mode */
            mode: string;
            /** Generated At */
            generated_at: string | null;
        };
        /** SyncStats */
        SyncStats: {
            /** Received */
            received: number;
            /** Added */
            added: number;
            /** Price Changed */
            price_changed: number;
            /** Removed */
            removed: number;
            /** Reactivated */
            reactivated: number;
            /** Active Total */
            active_total: number;
        };
        /** TelegramLink */
        TelegramLink: {
            /** Url */
            url: string;
        };
        /** TelegramStatus */
        TelegramStatus: {
            /** Configured */
            configured: boolean;
            /** Linked */
            linked: boolean;
        };
        /** TokenIn */
        TokenIn: {
            /** Label */
            label?: string | null;
        };
        /**
         * TokenInfo
         * @description ما يُعرض عن مفتاح بعد إنشائه — البادئة للتعرّف عليه، لا المفتاح نفسه.
         */
        TokenInfo: {
            /** Token Id */
            token_id: string;
            /** Prefix */
            prefix: string;
            /** Label */
            label: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** UploadOut */
        UploadOut: {
            /** Dataset Id */
            dataset_id: string;
            /** Job Id */
            job_id: string;
            /** Duplicate Of */
            duplicate_of?: string | null;
        };
        /** UploadUrlIn */
        UploadUrlIn: {
            /** Filename */
            filename: string;
            /** Size */
            size: number;
        };
        /** UploadUrlOut */
        UploadUrlOut: {
            /** Dataset Id */
            dataset_id: string;
            /** Url */
            url: string;
            /**
             * Method
             * @default PUT
             */
            method: string;
            /**
             * Headers
             * @default {}
             */
            headers: {
                [key: string]: string;
            };
            /**
             * Expires In
             * @default 900
             */
            expires_in: number;
            /** Direct */
            direct: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WarehouseIn */
        WarehouseIn: {
            /** Name */
            name: string;
        };
        /** WarehouseOut */
        WarehouseOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Active Item Count */
            active_item_count: number;
            /** Last Sync At */
            last_sync_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latest Dataset Id */
            latest_dataset_id?: string | null;
        };
        /** TokenOut */
        apps__api__src__routers__auth__TokenOut: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TokenOut */
        apps__api__src__routers__sync__TokenOut: {
            /** Token Id */
            token_id: string;
            /** Prefix */
            prefix: string;
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apps__api__src__routers__auth__TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apps__api__src__routers__auth__TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apps__api__src__routers__auth__TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_url_datasets_upload_url_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_upload_uploads__ticket__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_datasets__dataset_id__complete_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_datasets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_concepts_datasets_concepts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptOut"][];
                };
            };
        };
    };
    list_currencies_datasets_currencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrencyOut"][];
                };
            };
        };
    };
    get_dataset_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_datasets__dataset_id__schema_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_schema_datasets__dataset_id__schema_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaPatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_datasets__dataset_id__profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cleaning_datasets__dataset_id__cleaning_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleaningOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_cleaning_datasets__dataset_id__cleaning_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleaningPatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaPatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_datasets__dataset_id__insights_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_jobs__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_datasets__dataset_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rows_datasets__dataset_id__rows_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                sort_by?: string | null;
                descending?: boolean;
                search?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RowsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_datasets__dataset_id__export_get: {
        parameters: {
            query?: {
                fmt?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestions_datasets__dataset_id__suggestions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_datasets__dataset_id__ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_warehouses_v1_warehouses_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_warehouse_v1_warehouses_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WarehouseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WarehouseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tokens_v1_warehouses__warehouse_id__tokens_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_token_v1_warehouses__warehouse_id__tokens_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["apps__api__src__routers__sync__TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_token_v1_warehouses__warehouse_id__tokens__token_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                warehouse_id: string;
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_syncs_v1_warehouses__warehouse_id__syncs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                warehouse_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_catalog_v1_sync_catalog_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description حمولة مكرّرة — المزامنة الأصلية */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOut"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_status_v1_alerts_telegram_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_unlink_v1_alerts_telegram_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_link_v1_alerts_telegram_link_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLink"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_verify_v1_alerts_telegram_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    internal_check_stale_v1_internal_check_stale_post: {
        parameters: {
            query?: never;
            header?: {
                "x-cron-secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaleCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
